import Head from "next/head";

export default function PageHead({ title }) {
  return (
    <Head>
      <title>Bandhani Trendz{title ? ` | ${title}` : ""}</title>
      <meta name="description" content="Generated by create next app" />

      <link
        key="180x180"
        rel="apple-touch-icon"
        sizes="180x180"
        href="/favicon/apple-touch-icon.png"
      />
      <link
        key="32x32"
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="/favicon/favicon-32x32.png"
      />
      <link
        key="16x16"
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="/favicon/favicon-16x16.png"
      />
      <link key="icon" rel="icon" href="/favicon/favicon.ico" />

      <link key="manifest" rel="manifest" href="/favicon/site.webmanifest" />
    </Head>
  );
}
