import Head from "next/head";

import Footer from "../../component/Footer";
import Navbar from "../../component/Navbar";
import TitleBar from "../../component/TitleBar";

import styles from "../../styles/Product.module.css";

export default function Product() {
  const catagories = [
    { title: "saree", url: "/categories?type=saree" },
    { title: "dress", url: "/categories?type=dress" },
    { title: "fabric", url: "/categories?type=fabric" },
    { title: "dupata", url: "/categories?type=dupata" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isTransparent={false} />

      <TitleBar items={catagories} />

      <main className={styles.main}></main>

      <Footer />
    </div>
  );
}
