import Head from "next/head";
import Image from "next/image";
import Navbar from "../component/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bandhani Trendz | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar isTransparent={true} />

      <main className={styles.main}>
        <section id={styles.heroSection} className="bg-gradient bg-pattern-1">
          <div className="wrapper two-section-wrapper ">
            <div className="left">
              <h2 className={styles.heroHeading}>Wide Range of Classic BANDHAJ Apparels</h2>
              <button className={"btn " + styles.exploreBtn}>Explore Now</button>
            </div>

            <div className="right">
              <div className={styles.imageWrapper}>
                <Image
                  className={styles.heroImage}
                  src="/assets/images/saree_4.jpeg"
                  width={350}
                  height={250}
                  layout="responsive"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
